--- 
name: bosh-cassandra-01
director_uuid: 4371259e-6f65-4e29-9e28-50e03e36c1bc

release:
  name: cassandra
  version: 0.6-dev

compilation:
  workers: 4
  cloud_properties:
    ram: 4096
    disk: 8096
    cpu: 4
  network: default
  reuse_compilation_vms: true 

update:
  canaries: 1
  canary_watch_time: 3000 - 300000
  update_watch_time: 3000 - 300000
  max_in_flight: 2
  max_errors: 1

networks:
 - name: default
   subnets:
   - reserved:
     - 10.13.219.2 - 10.13.219.80
     - 10.13.219.240 - 10.13.219.254
     static:
     - 10.13.219.107 - 10.13.219.159
     range: 10.13.219.0/24
     gateway: 10.13.219.1
     dns:
     - 10.254.66.23
     - 10.254.66.24
     cloud_properties:
      name : vLAN0583

resource_pools:
 - name: infrastructure
   network: default
   size: 3
   stemcell:
    name: bosh-stemcell
    version: 0.6.7
   cloud_properties:
    ram: 2048
    disk: 8192
    cpu: 1
   env:
    bosh:
      password: $6$2f6qtRfO$oJOeKk/ZDNb7PWnvMiXDC/HstKiLiZCBHP32KHFVeM9rXgs4W/JJiI4a/eHoddhxJzorLYgi2JUQiOKxZko4M.
      # c1oudc0w - password generated using mkpasswd -m sha-512


jobs: 
- name: cassandra
  template: cassandra
  instances: 3
  resource_pool: infrastructure
  persistent_disk: 128
  networks:
  - name: default
    static_ips:
    - 10.13.219.151-10.13.219.153


